update chaos infra to handle need for 3 deb (not just 1)
redpanda-data/chaos pull request #40
Opened 2024-04-25 22:04 UTC by jackietung-redpanda

At this point, we need these debs:
- redpanda
- redpanda-tuner
- redpanda-rpk

This PR plugs the gap for chaos tests. First reported [here](https://redpandadata.slack.com/archives/C06MCRY75U7/p1714049178702429).

[Change needed in vtools.git repo](https://github.com/redpanda-data/vtools/pull/2701) also (so extra DEB info gets piped through). But this PR can go in independently. Note chaos CI will only start working with both fixes.

2024-04-25 22:04 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/redpanda-data/chaos?pullRequest=40) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/redpanda-data/chaos?pullRequest=40) before we can accept your contribution.<br/><hr/>**Jackie Tung** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/redpanda-data/chaos?pullRequest=40) it.</sub>

2024-04-25 22:11 UTC, jackietung-redpanda commented on README.md
> +    ansible-playbook deploy.yml --key-file=./id_ed25519
`--key-file` points at the private ssh key generated by terraform.

2024-04-25 22:12 UTC, jackietung-redpanda commented on deploy.yml
> +        dpkg --force-confold -i  /mnt/vectorized/{{ rpk_deb_name }} /mnt/vectorized/{{ tuner_deb_name }} /mnt/vectorized/{{ deb_name }}
Locally tested: installs successfully.

2024-04-25 22:13 UTC, jackietung-redpanda commented on docker/rebuild4.sh
> +chmod -R a+rw ./docker/bind_mounts
On MacOS, `-R` needs to come first.  So let's do it the way that works on both MacOS and Linux.

2024-04-25 23:49 UTC, ivotron requested changes
same comment as in the other PR, this is going to break 23.x schedules

2024-04-26 23:24 UTC, ivotron approved these changes

2024-04-26 23:24 UTC, ivotron commented
@jackietung-redpanda can you please sign the CLA?

2024-04-29 23:19 UTC, merged